//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTransactionDeatilsMapping
    {
        public int CTMID { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public Nullable<decimal> CategoryID { get; set; }
        public Nullable<decimal> ProductID { get; set; }
        public string TransactionID { get; set; }
        public Nullable<decimal> VideoID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<decimal> DeletedBy { get; set; }
    }
}
