
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace University.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {

        this.Login_tbl = new HashSet<Login_tbl>();

    }


    public string CompanyName { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string ZIP { get; set; }

    public string ContactName { get; set; }

    public string ContactTelephone { get; set; }

    public string ContactEmail { get; set; }

    public Nullable<decimal> CurrencyBaseUnit { get; set; }

    public string CCTerminalID { get; set; }

    public string CCTransactionKey { get; set; }

    public string CCClearingPlatform { get; set; }

    public Nullable<decimal> TimeZone { get; set; }

    public Nullable<decimal> DSTAdjust { get; set; }

    public Nullable<System.DateTime> DateTimeCreated { get; set; }

    public Nullable<System.DateTime> DateTimeModified { get; set; }

    public Nullable<double> MediumCashBoxValuePriority { get; set; }

    public Nullable<double> HighCashBoxValuePriority { get; set; }

    public Nullable<int> CoinBoxVolume { get; set; }

    public string ImageLogoPath { get; set; }

    public Nullable<decimal> BankReconOffset { get; set; }

    public Nullable<decimal> CoinAcceptanceRateThreshold { get; set; }

    public Nullable<decimal> CCTransactionFee { get; set; }

    public Nullable<decimal> SecureGatewayFee { get; set; }

    public Nullable<decimal> ManagementSystemFee { get; set; }

    public Nullable<bool> CustomerActive { get; set; }

    public Nullable<bool> CustomerBillable { get; set; }

    public string PaymentProcessor { get; set; }

    public string DailyNotificationsEmail { get; set; }

    public string BillingEmail { get; set; }

    public string CurrencyCode { get; set; }

    public Nullable<int> CountryID { get; set; }

    public string DefaultLanguage { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<decimal> WebUserIDCreated { get; set; }

    public Nullable<decimal> WebUserIDModified { get; set; }

    public bool IsSmartCardUsed { get; set; }

    public Nullable<int> CCUserID { get; set; }

    public string AccessCardCustomer { get; set; }

    public string AccessCardAddress { get; set; }

    public string AccessCardCity { get; set; }

    public string AccessCardState { get; set; }

    public string AccessCardZIP { get; set; }

    public Nullable<bool> ObservesDST { get; set; }

    public Nullable<int> Alerts { get; set; }

    public Nullable<decimal> CCFee { get; set; }

    public decimal CustomerID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Login_tbl> Login_tbl { get; set; }

}

}
