//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDocuments
    {
        public decimal Id { get; set; }
        public string Title { get; set; }
        public string Decription { get; set; }
        public string DocumentURL { get; set; }
        public string DocumentDisplayName { get; set; }
        public decimal ProductId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<decimal> DeletedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public Nullable<int> AssocitedCustID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
